// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXevY5aCk0TA_RuzgG6RU95jfStSBk6Go',
    appId: '1:390976943192:web:deeba78974d63fd409c62d',
    messagingSenderId: '390976943192',
    projectId: 'prjkt-73852',
    authDomain: 'prjkt-73852.firebaseapp.com',
    storageBucket: 'prjkt-73852.appspot.com',
    measurementId: 'G-63555MEJ58',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0ytqXurGIw8FW8HJdN04ON29fj-2i7i4',
    appId: '1:390976943192:android:007f7bf3299a40c709c62d',
    messagingSenderId: '390976943192',
    projectId: 'prjkt-73852',
    storageBucket: 'prjkt-73852.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBej3QizQT2olAo9pRVBd9WnQD6KarQo0U',
    appId: '1:390976943192:ios:578c4879548106bb09c62d',
    messagingSenderId: '390976943192',
    projectId: 'prjkt-73852',
    storageBucket: 'prjkt-73852.appspot.com',
    iosBundleId: 'com.example.firebaseProject1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBej3QizQT2olAo9pRVBd9WnQD6KarQo0U',
    appId: '1:390976943192:ios:578c4879548106bb09c62d',
    messagingSenderId: '390976943192',
    projectId: 'prjkt-73852',
    storageBucket: 'prjkt-73852.appspot.com',
    iosBundleId: 'com.example.firebaseProject1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXevY5aCk0TA_RuzgG6RU95jfStSBk6Go',
    appId: '1:390976943192:web:9cf7a7bf7739879309c62d',
    messagingSenderId: '390976943192',
    projectId: 'prjkt-73852',
    authDomain: 'prjkt-73852.firebaseapp.com',
    storageBucket: 'prjkt-73852.appspot.com',
    measurementId: 'G-63E8SDM336',
  );
}
