// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRhyz0FOFNZJiJH_ToXRV5kwl2MavwX3o',
    appId: '1:872247734923:web:b7ba3ab8b15f8fc6015a8e',
    messagingSenderId: '872247734923',
    projectId: 'navtcc-project',
    authDomain: 'navtcc-project.firebaseapp.com',
    storageBucket: 'navtcc-project.appspot.com',
    measurementId: 'G-50YL1YXNKQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZOz-FC70p7suRe42UOu-721JG0f45I-E',
    appId: '1:872247734923:android:d10b00b035882505015a8e',
    messagingSenderId: '872247734923',
    projectId: 'navtcc-project',
    storageBucket: 'navtcc-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNf8-CUgrrZO0qg7LI6RlCSHe-EgnEfE8',
    appId: '1:872247734923:ios:ce0cfdb439408907015a8e',
    messagingSenderId: '872247734923',
    projectId: 'navtcc-project',
    storageBucket: 'navtcc-project.appspot.com',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNf8-CUgrrZO0qg7LI6RlCSHe-EgnEfE8',
    appId: '1:872247734923:ios:ce0cfdb439408907015a8e',
    messagingSenderId: '872247734923',
    projectId: 'navtcc-project',
    storageBucket: 'navtcc-project.appspot.com',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRhyz0FOFNZJiJH_ToXRV5kwl2MavwX3o',
    appId: '1:872247734923:web:dfa96a91d8639e69015a8e',
    messagingSenderId: '872247734923',
    projectId: 'navtcc-project',
    authDomain: 'navtcc-project.firebaseapp.com',
    storageBucket: 'navtcc-project.appspot.com',
    measurementId: 'G-CP16B2PZY7',
  );

}